spring:
    application:
        name: solicitudes-service

    r2dbc:
        url: r2dbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
        username: username
        password: password

    flyway:
        enabled: true
        url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
        user: username
        password: password
        locations: classpath:db/migration

server:
    port: 8080
