spring:
    application:
        name: solicitudes-service

    r2dbc:
        url: ${DB_R2DBC_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    flyway:
        enabled: true
        url: ${DB_JDBC_URL}
        user: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        locations: classpath:db/migration

server:
    port: 8080
